# Generated by Django 2.2.2 on 2019-07-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_realtor',
            field=models.BooleanField(default=False),
        ),
    ]
