# Generated by Django 2.2.2 on 2019-07-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20190708_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
