# Generated by Django 2.2.2 on 2019-07-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20190708_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.CharField(max_length=100),
        ),
    ]
