# Generated by Django 2.2.2 on 2019-07-05 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_realtor_is_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
