# Generated by Django 2.2.2 on 2019-07-05 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0003_realtor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
