# Generated by Django 2.2.2 on 2019-07-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0004_realtor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
