# Generated by Django 2.2.2 on 2019-07-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0005_auto_20190705_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(upload_to='photos/%y/%m/%d/'),
        ),
    ]
