# Generated by Django 2.2.2 on 2019-07-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0007_auto_20190705_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
