# Generated by Django 2.2.2 on 2019-07-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0009_realtor_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='realtor',
            name='is_realtor',
        ),
        migrations.RemoveField(
            model_name='realtor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='realtor',
            name='username',
        ),
    ]
