# Generated by Django 2.2.2 on 2019-07-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0011_realtor_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='user_id',
            new_name='user',
        ),
    ]
