# Generated by Django 2.2.2 on 2019-07-08 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0012_auto_20190706_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
